.circleci/config.yml
`dash` pulling other `dash-*` installs prevents the table tests from running correctly as the latest production build is used instead of the branch test build.
Correct test run here: https://circleci.com/gh/plotly/dash-table/tree/pip-local-packages
=> Fix table tests

CHANGELOG.md, src/dash-table/components/ControlledTable/index.tsx, src/dash-table/components/HeaderFactory.tsx, src/dash-table/components/Table/index.tsx, src/dash-table/components/Table/props.ts, src/dash-table/dash/DataTable.js, src/dash-table/derived/data/virtual.ts, src/dash-table/derived/header/content.tsx, tests/cypress/dash/v_be_page.py, tests/dash/app_dataframe_backend_paging.py, tests/visual/percy-storybook/DashTable.percy.tsx
As discussed https://github.com/plotly/dash-table/pull/412#discussion_r278364448
=> change sorting_settings to sort_by

.config/webpack/base.js, .storybook/babel.config.js, .storybook/webpack.config.js, babel.config.js, package.json, src/dash-table/syntax-tree/SingleColumnSyntaxTree.ts, tests/cypress/tests/unit/edges_test.ts, webpack.dev.config.js, webpack.test.config.js
Keeping up with the latest and greatest of various dependencies. Been preventing this one from updating through the renovate bot for a while now as it causes a bunch of issues in the tests.
What's the point? Core-js is a library that polyfills newer ES201x functionalities into things the `@babel/env` target browsers will all be able to use.
Fixing all of those here!
=> Upgrade core js

src/core/comparer.ts, src/core/math/arrayZipMap.ts, src/core/math/matrixZipMap.ts, src/dash-table/components/Table/index.tsx, src/dash-table/derived/edges/index.ts, src/dash-table/derived/style/index.ts, tslint.json
This does 2 things:
1. Optimize the utility functions (mostly removing Ramda for/map/addIndex in favor of native `for` loops)
This drops average render time from ~50ms down to ~35ms.
2. Optimize the previously optimized edges & styles calculations (https://github.com/plotly/dash-table/pull/465). This is done by removing Ramda where possible and through some other optimizations.
This drops the average render time from ~35ms to ~23ms.
Reflow and react internals remain unchanged with ~100ms and ~50ms per render respectively while table `render` itself is slashed in half. This only represents a ~10% improvement.
At this point ~45% (~10-10.5ms) of the table's `render` time is accounted for by cache busting / checks on memoized functions.
=> Optimize utility functions

CHANGELOG.md, demo/AppMode.ts, src/dash-table/components/ControlledTable/index.tsx, src/dash-table/components/Table/Table.less, src/dash-table/components/Table/props.ts, src/dash-table/dash/DataTable.js, tests/visual/percy-storybook/Width.all.percy.tsx, tests/visual/percy-storybook/Width.defaults.percy.tsx, tests/visual/percy-storybook/Width.empty.percy.tsx, tests/visual/percy-storybook/Width.max.percy.tsx, tests/visual/percy-storybook/Width.min.percy.tsx, tests/visual/percy-storybook/Width.width.percy.tsx, tests/visual/percy-storybook/fixtures.ts
Fixes #489 and improves the nomenclature.
- Undo the regression introduced by removing `content_style` in #446 
- Rename the prop `fill_width` with now type `boolean` (True=grow, False=fit in previous prop)
=> Issue 489 - `content_style` regression

CHANGELOG.md, src/dash-table/components/Table/Table.less
Remove default tr background color.
=> Remove pre-defined background color for table row

CHANGELOG.md, src/dash-table/components/Table/Table.less
@alinastarkov found `-webkit-sticky`, just adding it and fixing a (would be) regression on fixed columns (when transparent)
=> Fix sticky behavior in Safari

CHANGELOG.md, demo/AppMode.ts, demo/data.ts, src/dash-table/derived/cell/contents.tsx, tests/cypress/tests/standalone/filtering_test.ts, tests/cypress/tests/standalone/readonly_sorting_test.ts, tests/cypress/tests/standalone/readwrite_sorting_test.ts, tests/visual/percy-storybook/Dropdown.percy.tsx
Closes #524. Fixes regression introduced by https://github.com/plotly/dash-table/pull/281.
- When using a label in-place of dropdown component, make sure to resolve the dropdown label instead of just displaying the value.
- Update tests so that labels are different from values, making testing for this error easier
- Additional visual tests
=> Issue 524 - Readonly dropdown column content

src/dash-table/dash/DataTable.js
The newlines and lists in the docstrings were making it difficult to read in the Python console; they have been replaced with semicolons/periods.
=> Remove newlines and lists from docstrings

CHANGELOG.md, demo/AppMode.ts, src/dash-table/utils/actions.js, tests/cypress/tests/standalone/edit_headers.ts
=> Allow renaming single-row headers

src/dash-table/components/ControlledTable/index.tsx, src/dash-table/derived/cell/operations.tsx, src/dash-table/derived/data/virtual.ts, src/dash-table/derived/header/content.tsx, src/dash-table/syntax-tree/lexicon/index.ts, src/dash-table/syntax-tree/lexicon/query.ts
@Marc-Andre-Rivet one more quickie to finish purging deprecated `R.contains` from our code. Amusingly `@types/ramda` didn't get the placeholder signatures for `R.includes` (yet? 🙄) but there's a more concise solution anyway...
=> convert R.contains to R.includes

CHANGELOG.md, src/dash-table/syntax-tree/SingleColumnSyntaxTree.ts, src/dash-table/syntax-tree/lexeme/relational.ts, tests/cypress/tests/unit/dash_table_queries_test.ts, tests/cypress/tests/unit/single_column_syntactic_tree_test.ts
Fixes #460 
- improve datestartswith operator handling of types
- fix issue where equal was incorrectly used on default operators
- add appropriate unit tests
=> Issue 460 - datestartswith relational operator behavior on number expression

CHANGELOG.md, src/core/syntax-tree/index.ts, src/core/syntax-tree/lexicon.ts, src/dash-table/syntax-tree/lexeme/expression.ts, src/dash-table/syntax-tree/lexeme/unary.ts, src/dash-table/syntax-tree/lexicon/column.ts, src/dash-table/syntax-tree/lexicon/columnMulti.ts, src/dash-table/syntax-tree/lexicon/query.ts, tests/cypress/tests/standalone/filtering_test.ts, tests/cypress/tests/unit/query_syntactic_tree_test.ts, tests/cypress/tests/unit/single_column_syntactic_tree_test.ts
#598
Allow more permissive expression value (with whitespaces without escaping or quotes) in column filters.
A limitation is that if it starts with an operator's text, the operator will be picked up instead. e.g `le jour` is `<= jour`, not `"le jour"`.
Added a test case for permissive strings. 
Added changelog entry.
#597 
New `is blank` unary operator that returns true for `undefined`, `null` and `''`.
In both cases, the documentation will need to be updated.
=> Issue 598 - Permissive value in filter

CHANGELOG.md, src/dash-table/components/ControlledTable/index.tsx, src/dash-table/type/reconcile.ts, tests/cypress/tests/unit/numberCoercion_test.ts, tests/cypress/tests/unit/numberValidation_test.ts, tests/cypress/tests/unit/reconcile_test.ts
Fixes #600 
The `delete cell` operation done through `backspace` on selected cells is already a bit confusing as it will delete content based on whether the column is editable or not. The additional changes to apply defaults is no less confusing but is at least it's aiming to be consistent with how the table would behave if you were to delete content for each cell individually.
=> Issue 600 - Incorrect cell validation / coercion

.gitignore, cspell.json
Fixes #610 
After this PR, developers using VSCode, would need to create their own project configuration. The only line that is needed is:
`"tslint.jsEnable": true`
=> Remove VSCode config from git

src/dash-table/dash/DataTable.js
just to remove the warning during build:
```
> dash-generate-components src/dash-table/dash/DataTable.js dash_table -p package-info.json && cp dash_table_base/** dash_table/ && dash-generate-components src/dash-table/dash/DataTable.js dash_table -p package-info.json --r-prefix 'dash'
Description for DataTable.setProps is missing!
Generated DataTable.py
Description for DataTable.setProps is missing!
Generated DataTable.py
Generated dashDataTable.R
```
=> description for setProps prop

CHANGELOG.md, demo/AppMode.ts, package-lock.json, src/dash-table/components/CellLabel/index.tsx, src/dash-table/derived/cell/contents.tsx, tests/cypress/tests/standalone/readonly_navigation_test.ts
Fixes #618 
New test, failure prior to fix: https://circleci.com/gh/plotly/dash-table/14271
Passes after fix: https://circleci.com/gh/plotly/dash-table/14278
=> Issue 618 - Keyboard navigation in sparsely readonly table

CHANGELOG.md, src/core/Clipboard.ts, src/core/components/IsolatedInput/index.tsx, src/dash-table/components/Filter/Column.tsx, src/dash-table/utils/TableClipboardHelper.ts
Fixes #206 
Allow copy/paste from/to filter columns inputs.
**Note**: Sadly there's no good way to test this through Cypress. The table cell copy could be done because of the way the data is copied and pasted, could be shimmed with some tweaking. There's no clear path here.
=> Issue 206 - Filter copy/paste

CHANGELOG.md, src/dash-table/components/ControlledTable/fragments/TableTooltip.tsx
=> Issue 561 - Fix incorrect React PureComponent usage causing warnings

CHANGELOG.md, src/dash-table/components/ControlledTable/index.tsx, src/dash-table/utils/TableClipboardHelper.ts, src/dash-table/utils/applyClipboardToData.ts, tests/cypress/tests/unit/clipboard_test.ts
Fixes #611 
Similarly to what's being done elsewhere, the clipboard needs to take into consideration both the visible columns and all the available columns when handling a copy/paste operation.
The last visible column is used to determine placement and whether new columns are required, all columns are used to determine the final set of columns if new ones are needed and their final placement based on visible ones.
Added two tests to the clipboard to check the behavior when there are hidden columns.
=> Issue 611 - Hidden columns on copy/paste

dash_table_base/__init__.py, package-lock.json, package.json, src/dash-table/LazyLoader.ts, src/dash-table/dash/DataTable.js, src/dash-table/dash/fragments/DataTable.js
Follow up to https://github.com/plotly/dash/pull/973 to be completed and `@plotly/webpack-dash-dynamic-import` to be updated / published in order to be completed.
Makes the entire table component async. As the table has side-effects (like the dcc.Graph), it needs to inform the renderer by using the `@plotly/dash-component-plugins` decorator.
=> Async table component

CHANGELOG.md, src/dash-table/components/Table/derivedPropsHelper.ts, src/dash-table/components/Table/props.ts
The prop `derived_filter_query_structure` (https://github.com/plotly/dash-table/blob/dev/src/dash-table/dash/DataTable.js#L1149) was not triggering callbacks when `filter_query` changed. Updating the prop name in `derivedPropsHelper` (https://github.com/plotly/dash-table/blob/dev/src/dash-table/components/Table/derivedPropsHelper.ts#L64) fixed this.
=> Update naming of derived_filter_query_structure in derivedPropsHelper.

CHANGELOG.md, src/core/storage/Cookie.ts
When dash is embedded into an iframe with a sandbox attribute that only has allow-scripts, cookie access is disabled and dash-table fails to load. As such, we need to restrict our cookie usage by disabling functionality.
This patch removes the disabled functionality in a graceful manner, allowing dash-table to load in very restricted iframes.
=> feat: disable cookie access under restricted sandboxes

.circleci/config.yml, .config/webpack/base.js, CHANGELOG.md, MANIFEST.in, dash_table_base/__init__.py
=> Issue 703 - Rename async modules

CHANGELOG.md, dash-info.yaml
This PR proposes to add two simple examples to the `dashTable` package, which is suggested for CRAN submission. A vignette will eventually be included with far more relevant information, but this should be enough to get people going.
=> Contribute basic examples to dashTable package for R

CHANGELOG.md, src/dash-table/components/CellLabel/index.tsx, src/dash-table/components/Table/Table.less
Closes #526 
Closes #676 
This allows readonly cells to trigger a `copy` event in the table. This PR forces content selection, restyling selection so as to not show, and makes sure the cell content has focus.
Due to overrides necessary for Selenium and Cypress to behave correctly with copy/paste inside the table, it is not possible to automate this test. It has been documented in the manual tests section of https://github.com/plotly/dash-core/blob/master/Manual%20Testing.md
=> Issue 526 - Copy/paste does not work in certain situations

CHANGELOG.md, src/dash-table/dash/DataTable.js
Closes #651 by making it clear in the documentation for `active_cell` that `row_id` only appears when row IDs are defined, by the user.
Did confuse me for a while at least.
=> Issue 651 - Clarify optional nature of row_id in active_cell

CHANGELOG.md, pytest.ini, src/dash-table/components/Table/props.ts, src/dash-table/dash/DataTable.js, src/dash-table/dash/Sanitizer.ts, src/dash-table/dash/validate.ts, tests/selenium/test_empty.py
Closes #384 
Changes table validation/sanitation to handle `data=None` and `columns=None` without throwing an error.
=> Issue 384 - Handling of `None` data and columns props

CHANGELOG.md, src/dash-table/components/CellDropdown/index.tsx, tests/selenium/conftest.py, tests/selenium/test_dropdown.py
Closes #486 
Closes #672 
It seems that this was probably always broken.
Failing test run prior to fix: https://circleci.com/gh/plotly/dash-table/18036
Passing test run with the fix: https://circleci.com/gh/plotly/dash-table/18044
=> Issue 486 - Don't scroll menu into view

man/df_to_list.Rd
This PR proposes to make the `df_to_list` example runnable for CRAN submission, and to add a `\value` tag, which they have also requested.
This should merge into `master`, since `df_to_list` does not exist in `dev`.
=> Update Rd file for df_to_list for CRAN

man/df_to_list.Rd
This PR proposes to eliminate `=NULL` from the `\usage` block within `df_to_list.Rd`. Currently, there is a minor discrepancy between the documented usage and the actual usage, which causes the following error to occur upon running `R CMD check --as-cran`:
```
* checking for code/documentation mismatches ... WARNING
Codoc mismatches from documentation object 'df_to_list':
df_to_list
Code: function(df)
Docs: function(df = NULL)
Mismatches in argument default values:
Name: 'df' Code:  Docs: NULL
```
=> Fix usage entry within df_to_list.Rd

.circleci/config.yml, CHANGELOG.md, src/dash-table/components/CellMarkdown/index.tsx, src/dash-table/components/EdgeFactory.tsx, src/dash-table/components/Table/props.ts, src/dash-table/dash/DataTable.js, src/dash-table/dash/Sanitizer.ts, src/dash-table/derived/cell/wrapperStyles.ts, src/dash-table/handlers/cellEvents.ts, src/dash-table/utils/Markdown.ts, src/dash-table/utils/MarkdownHighlighter.tsx, tests/cypress/tests/standalone/markdown_test.ts, tests/selenium/test_markdown_link.py, tests/selenium/test_navigation.py, tests/visual/percy-storybook/Style.percy.tsx
Closes #710 
- Changes the behavior of markdown cells so that clicking on the cell both selects the cell and `click through` to the underlying element
- Changes the default markdown link target to `target=_blank` to open a new tab
- New `cell_selectable` prop (default: True) that turns on/off the ability to select and navigate cells in the table (also overrides value of `active_cell` and `selected_cells` during the sanitation phase)
=> Issue 710 - Markdown link click

CHANGELOG.md, src/dash-table/components/ControlledTable/index.tsx, tests/selenium/test_sizing.py
=> [WIP] Issue 797 - Misaligned rows after callback

CHANGELOG.md, src/core/objPropsToCamel.ts, src/dash-table/components/CellFactory.tsx, src/dash-table/components/CellMarkdown/index.tsx, src/dash-table/components/Table/props.ts, src/dash-table/dash/DataTable.js, src/dash-table/derived/cell/contents.tsx, src/dash-table/derived/style/py2jsCssProperties.ts, src/dash-table/utils/Markdown.ts, tests/selenium/test_markdown_link.py
Fixes #807 
Allows configuring markdown options at the table-level and will be compatible with future extensions if/when markdown support is increased.
Use the following value to open links in the current tab and get the behaviour as before #787 
```
markdown_options={"linkTarget": "_self"}
```
=> Issue 807 - Customizable Markdown options

CHANGELOG.md, src/dash-table/components/ControlledTable/index.tsx, tests/selenium/test_basic_copy_paste.py
=> Issue 790 - Copy/paste regression when selecting cells with mouse

CHANGELOG.md, src/dash-table/components/ControlledTable/fragments/TableTooltip.tsx, src/dash-table/components/tooltipHelper.ts, tests/selenium/test_tooltip.py
Fixes #736 issues not addressed by https://github.com/plotly/dash-table/pull/817 - namely tooltip misalignment when the table columns and rows are not "fixed".
=> Issue 736 - Misaligned tooltip (revisited)

CHANGELOG.md, dash_table_base/__init__.py
Companion to https://github.com/plotly/dash/pull/1493, see https://github.com/plotly/dash/issues/1143
=> improve dash import test

.circleci/config.yml, dash_table_base/__init__.py, dev-requirements.txt, requirements.txt
sanity for https://github.com/plotly/dash/pull/1506
=> use dash loosen-testing-reqs branch and fix linting

.circleci/config.yml
Companion to https://github.com/plotly/dash/pull/1507
Need to revert back dash branch when merged.
=> Updating CI Python images

CHANGELOG.md, src/dash-table/components/Table/props.ts, src/dash-table/dash/DataTable.js, tests/selenium/test_markdown_html.py
closes #915
closes #800
This pull request allows for the use html tags in markdown text.
As discussed [here in in #915](https://github.com/plotly/dash-table/issues/915#issuecomment-866281607) DataTable uses Remarkable for its markdown and the default is set to disable html input, probably to reduce XSS vulnerabilities.  This PR adds the  `html` option to `markdown_options` prop to make it possible to "opt in" and allow html in markdown.
I found [this reported security issue](https://snyk.io/vuln/SNYK-JS-REMARKABLE-174641)  with Remarkable which was fixed in 2019 in version 1.7.2. DashTable currently uses version ^2.0.1. I'm not sure I understand the XSS risks -- I think this would be a good topic to include in the docs. Would there be less risk if the markdown columns are not editable …
=> Allow HTML content in Markdown cells
